apiVersion: apps/v1
kind: Deployment
metadata:
  name: khp-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: khp-hello-world
  template:
    metadata:
      labels:
        app: khp-hello-world
    spec:
      containers:
        - name: khp-hello-world-server
          image: ghcr.io/khampeep/kp-virus
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: khp-hello-world-service
  labels:
    app: khp-hello-world-service
spec:
  selector:
    app: khp-hello-world
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP